# Site settings
title: Hello!
email: devendra.aaru@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    I am DevNaga, a programmer, gamer and an introvert.
baseurl: "/example" # the subpath of your site, e.g. /blog/
url: "http://devnaga.github.io" # the base hostname & protocol for your site
twitter_username: ""
github_username:  devnaga

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
